[package]
name = "gtk_test"
version = "0.1.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
edition = "2018"
[dependencies]
gtk-sys="*"
glib-sys="*"

[dependencies.gtk]
version = ""
features = ["v3_16"]
