[package]
name = "rust_app"
version = "0.1.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
app_dirs = { package = "app_dirs2", version = "2" }