[package]
name = "flaunch_cli"
version = "0.1.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
edition = "2018"

[dependencies]
flaunch_core = { path = "../flaunch_core" }
app_dirs = { package = "app_dirs2", version = "*" }
notify = "*"
clap ="*"
