[package]
name = "flaunch"
version = "0.1.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
edition = "2018"

[dependencies]
flaunch_core = { path = "../flaunch_core" }
flaunch_ui = { path = "../flaunch_ui" }
