name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install GTK3 dev packages
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev -o Acquire::Retries=3 && cargo install cargo-deb
    - name: checkout git repo
      uses: actions/checkout@v2
    - run: cargo build --release
    - name: packaging .deb archive
      run: cargo deb -p flaunch --no-build
    - name: Archive deb package
      uses: actions/upload-artifact@v2
      with:
        name: flaunch deb package
        path: target/debian/*.deb
  
  tests:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Zinstrument-coverage"
      LLVM_PROFILE_FILE: "flaunch-%p-%m.profraw"
      RUSTC_BOOTSTRAP: 1
    steps:
    - name: install GTK3 dev packages
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev -o Acquire::Retries=3 && rustup component add llvm-tools-preview && cargo install grcov
    - name: checkout git repo
      uses: actions/checkout@v2
    - run: cargo test
    - name: generate report
      run: grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/
    - name: Archive deb package
      uses: actions/upload-artifact@v2
      with:
        name: coverage report
        path: ./target/debug/coverage/*
