[package]
name = "pocketrocket_napi"
version = "0.1.0"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1.0"
napi-derive = "1.0"

[build-dependencies]
napi-build = "1.0"